### ISSUE TITLE
es6 modules spec seems to contradict itself

### ISSUE THREAD

**Issue by onlywei** [bmeck/node-eps#1]
Just wondering if I am going crazy or not reading this, but these two code snippets seem to me like they are in direct contradiction with each other:

https://github.com/bmeck/node-eps/blame/es6-module/002-es6-modules.md#L109
https://github.com/bmeck/node-eps/blame/es6-module/002-es6-modules.md#L235

The first snippet  says that `import './foo'` will not find `./foo.js`, but the second snippet is using `import './cjs'` to import `./cjs.js`. Am I missing something?

**Comment by bmeck** [comment]
you are not going crazy, this is a mistake and typo, fixing.

**Comment by bmeck** [comment]
fixed in dda631f59fd5d3f5bedf9d397fe5d50d50f43ebe
